# hCooldown (HKNGLGN)
# A lightweight cooldown plugin that adds cooldown to interact and click events to prevent lag.

messages:
  prefix: '&8[&3hCooldown&8]&r'
  no-permission: '%prefix% &cYou do not have permission to do that.'
  plugin-reloaded: '%prefix% &aPlugin has been reloaded.'

# WARN TYPES
# 1 = ACTIONBAR, 2 = CHAT
warn-type: 1

interact:
  enabled: true
  cooldown: 3
  check:
    item-meta: true
  warn:
    enabled: true
    message: '&e&lYOU HAVE TO WAIT &d&l%seconds% SECONDS &e&lBEFORE INTERACT AGAIN!'

inventory-click:
  enabled: true
  cooldown: 3
  check:
    item-meta: true
  warn:
    enabled: true
    message: '&e&lYOU HAVE TO WAIT &d&l%seconds% SECONDS &e&lBEFORE INTERACT AGAIN!'

citizens-click:
  enabled: false
  cooldown: 3
  check:
    right-click: true
    left-click: false # TODO
  warn:
    enabled: true
    message: '&e&lYOU HAVE TO WAIT &d&l%seconds% SECONDS &e&lBEFORE INTERACT AGAIN!'