name: hCooldown
version: 0.0.5
author: HKNGLGN
description: A lightweight cooldown plugin that adds cooldown to interact and click events to prevent lag.

softdepend: [HamsterAPI, Citizens]

main: io.github.hakangulgen.hcooldown.hCooldownPlugin

commands:
  hcooldown:
    aliases: [hcd]
    description: Main plugin command.